### ISSUE TITLE
[feat] Should signup users using unique email and valid password (front-end)

### ISSUE THREAD

**Issue by bumblebees1111** [bumblebees1111/carpool#16]
**Background**
Our website should be able to signup any user with a unique email address and valid password

---

**Scope**
This is a complex feat which involves frontend, backend and database. 

The frontend should provide a clear and concise entry point that allows users to input sign-up info, along with validation. Additionally, the frontend should be able to display the error message, including invalid inputs and error that comes from the backend.

---

**Tasks**
- [x] Create the sign-up component
- [x] Implement Formik and Yup to validate input info, handle changes and submit
- [x] Create GraphQL HOC to do the query/ mutation
- [ ] Generate GraphQL interface

---

**Additional context**
Impact: High
Complexity: Med
Effort: Med
