### ISSUE TITLE
[feat] Should signup users using unique email and valid password (back-end)

### ISSUE THREAD

**Issue by bumblebees1111** [bumblebees1111/carpool#17]
**Background**
Our website should be able to signup any user with a unique email address and valid password

---

**Scope**
This is a complex feat which involves frontend, backend and database. 

The backend should be able to interact with the database, to store the user info that comes from the frontend, along with exception handlers.

If necessary, update the database schema.

---

**Tasks**
- [ ] Create GraphQL schema on the backend, including resolver, mutation
- [ ] Update existing repositories and services
- [ ] Implement exception handler on the backend
- [ ] Implement Auth feature on the backend, block the visibility of the pages to the Guest user except for Home, login and sign up page 
- [ ] Implement JSON web token feature, a user toker must be expired after a period of time if the user doesn't log out explicitly. If the user comes back before the token expired, the back server should be able to extend the expired date
- [ ] Generate token when user login verified
- [ ] Add validator on each controller, any invalid input should be detected and the error message should be thrown.

---

**Additional context**
Impact: High
Complexity: Med
Effort: Med
